extendingUserModel/employeesApp/employeesApp/employees/urls.py
from django.urls import path
from employeesApp.employees import views
from employeesApp.employees.views import CreateEmployee, EmployeeDetails, EmployeesList

urlpatterns = [
    path('', EmployeesList.as_view(), name='employees list'),
    path('create/', CreateEmployee.as_view(), name='create employee'),
    path('details/<int:pk>/', EmployeeDetails.as_view(), name='employee details'),
    path('<int:pk>/delete/', views.DeleteEmployee.as_view(), name='delete employee'),
]

extendingUserModel/employeesApp/employeesApp/urls.py
from django.contrib import admin
from django.urls import path, include

from employeesApp import employees

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employeesApp.common.urls')),
    path('departments/', include('employeesApp.departments.urls')),
    path('employees/', include('employeesApp.employees.urls')),
    path('accounts/', include('employeesApp.accounts.urls')),
]

extendingUserModel/employeesApp/employeesApp/employees/models.py
from django.db import models

from employeesApp.departments.models import Department


class Employee(models.Model):
    class PositionChoices(models.TextChoices):
        STAFF = 'Staff', 'Staff'
        MANAGER = 'Manager', 'Manager'

    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100, choices=PositionChoices.choices)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

extendingUserModel/employeesApp/employeesApp/employees/forms.py
from django import forms

from employeesApp.employees.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

        error_messages = {
            'first_name': {
                'required': 'Please enter your first name.',
                'max_length': 'First name cannot exceed 100 characters.',
            },
        }


class EmployeeDeleteForm(EmployeeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].disabled = True


class EmployeeSearchForm(forms.Form):
    # TODO fix the SearchForm
    query = forms.CharField(
        label='Search Employees',
        max_length=100,
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Search Employees'}
        )
    )


class EmployeeFeedbackForm(forms.Form):
    author_name = forms.CharField(max_length=100)
    comment = forms.CharField(widget=forms.Textarea)

extendingUserModel/employeesApp/employeesApp/employees/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView

from employeesApp.employees.forms import EmployeeForm, EmployeeDeleteForm, EmployeeFeedbackForm
from employeesApp.employees.models import Employee


class EmployeesList(ListView):
    model = Employee
    context_object_name = 'employees'
    template_name = 'employees/employees-list.html'
    paginate_by = 3

    def get_queryset(self):
        return Employee.objects.all()


class EmployeeDetails(DetailView):
    model = Employee
    template_name = 'employees/employee-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feedback_form'] = EmployeeFeedbackForm()
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'POST':
            return self.post(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = EmployeeFeedbackForm(request.POST)

        print("Post method called")
        print("Form data:", request.POST)

        if form.is_valid():
            print("Form is valid.")
            print("Cleaned data:", form.cleaned_data)
            messages.success(request, 'Thank you for your feedback!')
            # return self.get(request, *args, **kwargs)  # Redirect back to the detail view
            return redirect('employees list')


        else:
            print("Form is invalid.")
            print("Errors:", form.errors)
            messages.error(request, 'There were errors in your submission. Please correct them.')
            context = self.get_context_data(feedback_form=form)  # Pass the form with errors
            return self.render_to_response(context)


class CreateEmployee(PermissionRequiredMixin, CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'employees/create-employee.html'
    success_url = reverse_lazy('employees list')
    permission_required = 'employees.add_employee'


class DeleteEmployee(PermissionRequiredMixin, DeleteView):
    model = Employee
    form_class = EmployeeDeleteForm
    template_name = 'employees/delete-employee.html'
    success_url = reverse_lazy('employees list')

    def get_initial(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        employee = Employee.objects.get(pk=pk)
        return employee.__dict__

extendingUserModel/employeesApp/templates/employees/create-employee.html
{% extends 'base.html' %}

{% block title %}
    Create Employee
{% endblock %}

{% block content %}
    {% include 'nav-bar.html' %}
    <h1>This Is The Create Employee Page</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Employee</button>
    </form>
{% endblock %}

extendingUserModel/employeesApp/templates/employees/delete-employee.html
{% extends 'base.html' %}

{% block title %}
    Delete Employee
{% endblock %}

{% block content %}
    {% include 'common/../nav-bar.html' %}
    <h1>This Is The Delete Employee Page</h1>

    {#    <a href="{% url 'delete employee' employee.pk %}">Delete Employee</a>#}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Delete Employee</button>
    </form>

{% endblock %}

extendingUserModel/employeesApp/templates/employees/employee-details.html
{% extends 'base.html' %}

{% block title %}
    Employee Details
{% endblock %}

{% block content %}
    {% include 'common/../nav-bar.html' %}

    <h1>This Is The Employee Details Page</h1>

    <div>
        <p>{{ employee.first_name }} {{ employee.last_name }}</p>
        <p>Works as {{ employee.position }}</p>
        <p>In the {{ employee.department }} department </p>

        <h2>Leave Your Feedback</h2>
        <form method="post" action="{% url 'employee details' employee.pk %}">
            {% csrf_token %}
            {{ feedback_form.as_p }}
            <button type="submit">Submit</button>
        </form>

        {% if perms.employees.delete_employee %}
            <a href="{% url 'delete employee' employee.pk %}">Delete</a>
        {% endif %}

    </div>


{% endblock %}

extendingUserModel/employeesApp/templates/employees/employees-list.html
{% extends 'base.html' %}

{% block title %}
    Employees List
{% endblock %}

{% block content %}
    {% include 'common/../nav-bar.html' %}
    <h1>This Is The Employees List Page</h1>

    <h2>Employees</h2>
    <ul>
        {% for employee in employees %}
            <li>
                {{ employee.first_name }} {{ employee.last_name }}
                <a href="{% url 'employee details' employee.pk %}">Details</a>
            </li>
        {% endfor %}
    </ul>

    <div class="pagination">    
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
         </span>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    {% if perms.employees.add_employee %}
        <a href="{% url 'create employee' %}">Add Employee</a>
    {% endif %}

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <form method="get">
        {% csrf_token %}
        {{ employee_search_form }}
        <button type="submit">Search</button>
    </form>

{% endblock %}